### PR TITLE
viewer: generic download

### LINKED ISSUE #190: viewer: incorrect error message on non-existing resource
Trying to access a nonexistent resource (through some dead link or because of a spelling mistake) results in "Unknown item type" being displayed. This is incorrect and we should instead display the proper error corresponding to this case.

### LINKED ISSUE #209: viewer: handle "other" item type
With a generic view allowing the user to at least download the file.

### PR DESCRIPTION
**Pull request by pacien**
See various commit messages.

GitHub: closes #190, closes #209

### CODE REVIEW

File: viewer/src/components/LdDownload.vue [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+  </div>
+</template>
+
+<script lang="ts">
+import { Component, Prop, Vue } from "vue-property-decorator";
+
+@Component export default class LdDownload extends Vue {
+  @Prop({ required: true }) readonly item!: Gallery.Item;
+
+  get itemResource(): string {
```
Comment (OzoneGrif) [inline viewer/src/components/LdDownload.vue:37]: Use a method directly instead of a getter. Then call the method (with parenthesis) in the template.

Comment (pacien) [reply viewer/src/components/LdDownload.vue:37]: Any particular reason to use one instead of the other? Is there any caveat in using getters?

File: viewer/src/components/LdDownload.vue [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+      <div>{{ $t("download.download-file-fmt", [itemFileName]) }}</div>
+    </a>
+  </div>
+</template>
+
+<script lang="ts">
+import { Component, Prop, Vue } from "vue-property-decorator";
+
+@Component export default class LdDownload extends Vue {
+  @Prop({ required: true }) readonly item!: Gallery.Item;
```
Comment (OzoneGrif) [inline viewer/src/components/LdDownload.vue:35]: If this component is reserved for other items, this prop should be of type: `Gallery.Other`

File: viewer/src/components/LdDownload.vue [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+
+  get itemResource(): string {
+    return (this.item.properties as Gallery.OtherProperties).resource;
```
Comment (OzoneGrif) [inline viewer/src/components/LdDownload.vue:38]: Unchecked cast, use the correct prop type instead.

File: viewer/src/views/GalleryNavigation.vue [hunk 4]
```diff
@@ -52,8 +48,25 @@ export default class GalleryNavigation extends Vue {
...
+        return this.query.length > 0
+          ? { component: "gallery-search", properties: { path: this.path } }
+          : { component: "gallery-directory", properties: { directory: this.$galleryStore.currentItem } };
+
+      case "picture":
+        return { component: "ld-picture", properties: { picture: this.$galleryStore.currentItem } };
+
+      default:
+        return { component: "ld-download", properties: { item: this.$galleryStore.currentItem } };
+    }
```
Comment (OzoneGrif) [inline viewer/src/views/GalleryNavigation.vue:69]: Although being interesting, I don't see the point of this change.

The former code was simpler and more typed/strict than the new code.

File: viewer/src/components/LdDownload.vue (hunk 1 above)
Comment (OzoneGrif) [reply viewer/src/components/LdDownload.vue:37]: it's less readable, by experience. Otherwise it works very similarly. For code uniformisation, I now avoid getters as much as possible.

File: viewer/src/components/LdDownload.vue [hunk 5]
```diff
@@ -0,0 +1,67 @@
...
+  }
+
+  get itemFileName(): string {
+    const timeStamped = this.itemResource.split("/").pop() ?? "";
+    return timeStamped.split("?")[0];
+  }
```
[the remark this answers is not in the document]
Comment (pacien) [reply viewer/src/components/LdDownload.vue:44]: > Works in our current situation, but could fail if the parameter changes. I would use a Regex to capture the correct group. Is it really necessary?

This gets the content between the last "/" and "?". Using a regexp for that is just a matter of taste that doesn't bring any advantage.

> The URL should contain the file, and browsers extract that filename automatically.

This is to exlude the timestamp from both the saved file and the displayed filename.

File: viewer/src/components/LdError.vue [hunk 6]
```diff
@@ -0,0 +1,64 @@
...
+    </div>
+  </div>
+</template>
+
+<script lang="ts">
+import { Component, Prop, Vue } from "vue-property-decorator";
+
+@Component export default class LdError extends Vue {
+  @Prop({ required: true }) readonly icon!: string;
+  @Prop({ required: true }) readonly message!: string;
```
[the remark this answers is not in the document]
Comment (pacien) [reply viewer/src/components/LdError.vue:35]: Is it "VueI18n.TranslateResult"?

[the remark this answers is not in the document]
Comment (OzoneGrif) [reply viewer/src/components/LdError.vue:35]: Yes, but if you use the proper constructor in the Prop, it should convert it to a String. That's mostly to inform you of this specificity.

File: viewer/src/components/LdError.vue [hunk 7]
```diff
@@ -0,0 +1,64 @@
...
+
+<style lang="scss" module>
+@import "~@/assets/scss/theme.scss";
+
+.container {
+  min-height: 100%;
+  display: flex;
+  align-items: center;
+  justify-content: center;
+}
```
[the remark this answers is not in the document]
Comment (pacien) [reply viewer/src/components/LdError.vue:47]: That's overfactoring. Spreading the declaration only makes it harder to debug and undertand the interactions between the finicky flex parameters.

I'd agree for common UI elements, but we're talking about handlers for which independence is actually desirable. Self-consistency in a module is more important than application-wide consistency for the item viewers. Keep in mind that we don't have ways of checking when things break automatically.

Also notice that this is a CSS module.

File: viewer/src/views/GalleryNavigation.vue (hunk 4 above)
Comment (pacien) [reply viewer/src/views/GalleryNavigation.vue:69]: Note the previous approach wasn't typed either. I wish that TypeScript had some form of pattern matching available but this isn't the case. I still find the switch-case statement to be clearer than the chain of conditional elements in the template, in particular with respect to the mutual exclusion based on the type of item.

Comment (OzoneGrif) [reply viewer/src/views/GalleryNavigation.vue:69]: Props are partially typed if you use the right plugin (I don't know about Webstorm).
With your switch, all types are destroyed and errors will occur at runtime.

The template is a lot clearer, also more performant since it's compiled, not your switch case. You can use `v-else-if` for mutual exclusions, but since it's impossible with how we type objects, I didn't find it necessary.

Comment (pacien) [reply viewer/src/views/GalleryNavigation.vue:69]: Ok. Is there a way to keep it somewhat typed while still using a dispatching function? I'd like to be able to load components dynamically for heavier item type handlers in the future.

File: viewer/src/components/LdError.vue (hunk 7 above)
[the remark this answers is not in the document]
Comment (OzoneGrif) [reply viewer/src/components/LdError.vue:47]: I disagree, that's not overfactoring. I've seen plenty of web application become unmaintainable because of diverging yet similar CSS declarations.

The CSS between both components is 100% identical for these two containers, if not in an import, use a global CSS declaration.

File: viewer/src/views/GalleryNavigation.vue (hunk 4 above)
Comment (OzoneGrif) [reply viewer/src/views/GalleryNavigation.vue:69]: No there are no way to do that properly.

Use the templates, they are fast (statically compiled), type-checked (for native types), and they dispatch to the right component with the proper directive `v-if`.

File: viewer/src/components/LdError.vue (hunk 7 above)
[the remark this answers is not in the document]
Comment (pacien) [reply viewer/src/components/LdError.vue:47]: I can turn this whole declaration global as ".centering-container" but chunking it into the multiple mono-property classes already defined in the global file and then re-composing them would be madness. Is this ok for you?

File: viewer/src/views/GalleryNavigation.vue (hunk 4 above)
Comment (pacien) [reply viewer/src/views/GalleryNavigation.vue:69]: So, no hope for loadable item type viewers through plugins?

File: viewer/src/components/LdDownload.vue (hunk 1 above)
Comment (pacien) [reply viewer/src/components/LdDownload.vue:37]: So they'd be functionally identical in this context?

Comment (pacien) [reply viewer/src/components/LdDownload.vue:37]: Solved: different on some edge cases, it's more prudent to use the computed value instead of getter with VueX.

File: viewer/src/views/GalleryNavigation.vue (hunk 4 above)
Comment (pacien) [reply viewer/src/views/GalleryNavigation.vue:69]: Let's put that back in a template if-else-chain and have the plugin system done in another ticket.

**Comment by pacien** [comment]
@OzoneGrif All concerns have been cleared. Please test and review again.

File: viewer/src/services/navigation.ts [hunk 8]
```diff
@@ -40,8 +40,8 @@ export default class Navigation {
   }
 
   // Checks if the type of an item matches
-  public static checkType(item: Gallery.Item | null, type: Gallery.ItemType): boolean {
-    return item?.properties.type === type ?? false;
+  public static checkType(item: Gallery.Item | null, type: Gallery.ItemType | null): boolean {
+    return item?.properties.type === type;
```
Comment (OzoneGrif) [inline viewer/src/services/navigation.ts:44]: `item?` may return undefined, and `undefined === null` returns false.
```suggestion
    return (item?.properties.type ?? null) === type;
```
